export const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirts",
      category: "shirts",
      image: "/images/nike-shirt.jpg",
      price: 150,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas fit shirt",
      slug: "adidas-fit-shirts",
      category: "shirts",
      image: "/images/adidas-shirt.jpg",
      price: 190,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Puma slim shirt",
      slug: "puma-fit-pant",
      category: "pants",
      image: "/images/puma-pant.jpg",
      price: 300,
      countInStock: 7,
      brand: "Puma",
      rating: 4.5,
      numReviews: 11,
      description: "high quality pant",
    },
    {
      name: "Aba slim shirt",
      slug: "aba-fit-pant",
      category: "pants",
      image: "/images/aba-shirt.jpg",
      price: 700,
      countInStock: 17,
      brand: "Aba",
      rating: 5.0,
      numReviews: 25,
      description: "high quality pant",
    },
  ],
};
