const FETCH_BEGIN = "FETCH_BEGIN";
const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_FAIL = "FETCH_FAIL";
const FETCH_SINGLE_BEGIN = "FETCH_SINGLE_BEGIN";
const FETCH_SINGLE_SUCCESS = "FETCH_SINGLE_SUCCESS";
const FETCH_SINGLE_FAIL = "FETCH_SINGLE_FAIL";

export {
  FETCH_BEGIN,
  FETCH_SUCCESS,
  FETCH_FAIL,
  FETCH_SINGLE_BEGIN,
  FETCH_SINGLE_SUCCESS,
  FETCH_SINGLE_FAIL,
};
