import bcrypt from "bcryptjs";
import { hashPassword } from "./bcrypt/bcrypt.mjs";

export const data = {
  users: [
    {
      name: "Mazi",
      email: "mazi@gmail.com",
      password: bcrypt.hashSync("mazi123"),
      // password: await hashPassword("mazi123"),
      isAdmin: true,
    },
    {
      name: "Okoro",
      email: "okoro@gmail.com",
      password: bcrypt.hashSync("okoro12345"),
      // password: await hashPassword("okoro12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: "1",
      name: "Nike slim shirt",
      slug: "nike-slim-shirts",
      category: "shirts",
      image: "/images/nike-shirt.jpg",
      price: 150,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: "2",
      name: "Adidas fit shirt",
      slug: "adidas-fit-shirts",
      category: "shirts",
      image: "/images/adidas-shirt.jpg",
      price: 190,
      countInStock: 15,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: "3",
      name: "Puma slim shirt",
      slug: "puma-fit-pant",
      category: "pants",
      image: "/images/puma-pant.jpg",
      price: 300,
      countInStock: 7,
      brand: "Puma",
      rating: 4.5,
      numReviews: 11,
      description: "high quality pant",
    },
    {
      // _id: "4",
      name: "Aba slim shirt",
      slug: "aba-fit-pant",
      category: "pants",
      image: "/images/aba-shirt.jpg",
      price: 700,
      countInStock: 17,
      brand: "Aba",
      rating: 5.0,
      numReviews: 25,
      description: "high quality pant",
    },
  ],
};
